image: python:3.5
test:
        script:
            - pip install coverage
            - coverage run --branch openweather.py
            - coverage report -m
            
test2:
        script:
                - python3 test_openweather.py
                - coverage run test_openweather.py
                - coverage report -m
            